controller_list:
  - name: fake_xarm7_controller
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint7
  - name: fake_xarm_gripper_controller
    joints:
      - drive_joint