controller_list:
  - name: fake_xarm5_controller
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5

  - name: fake_xarm_gripper_controller
    joints:
      - drive_joint